import type { FlightStatus, IFlightResponseData } from '@/services/external/aviation/aviation.types';

export const getCurrentCoordinates = (
	from: [number, number],
	to: [number, number],
	progressPercent: number
): { latitude: number; longitude: number } => {
	const ratio = progressPercent / 100
	const lat = from[0] + (to[0] - from[0]) * ratio
	const lng = from[1] + (to[1] - from[1]) * ratio
	return { latitude: lat, longitude: lng }
}


export const FLIGHTS: IFlightResponseData[] = [
  {
    flight_date: '2024-01-15',
    flight_status: 'active' as FlightStatus,
    departure: {
      airport: 'Sofia Airport',
      timezone: 'Europe/Sofia',
      iata: 'SOF',
      icao: 'LBSF',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T08:00:00+03:00',
      estimated: '2024-01-15T08:00:00+03:00',
      actual: '2024-01-15T08:00:00+03:00',
      estimated_runway: '2024-01-15T08:00:00+03:00',
      actual_runway: '2024-01-15T08:00:00+03:00',
    },
    arrival: {
      airport: 'Beijing Capital International Airport',
      timezone: 'Asia/Shanghai',
      iata: 'PEK',
      icao: 'ZBAA',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T22:00:00+08:00',
      estimated: '2024-01-15T22:00:00+08:00',
      actual: '',
      estimated_runway: '',
      actual_runway: '',
    },
    airline: {
      iata: 'TK',
      icao: 'THY',
      name: 'Turkish Airlines',
      logo: '/logos/turkish.svg'
    },
    flight: {
      number: '143',
      iata: 'TK143',
      icao: 'THY143',
      codeshared: {},
    },
    aircraft: {
      registration: 'TC-JFP',
      iata: 'A332',
      icao: 'A332',
      icao24: '',
    },
    live: {
      updated: new Date().toISOString(),
      latitude: 42.6959,   // getCurrentCoordinates result — подставь реальные если нужно
      longitude: 23.3964,
      altitude: 10600,
      direction: 0,
      speed_horizontal: 870,
      speed_vertical: 0,
      is_ground: false,
    },
    progress: 65,
  },
  {
    flight_date: '2024-01-15',
    flight_status: 'active' as FlightStatus,
    departure: {
      airport: 'Dublin Airport',
      timezone: 'Europe/Dublin',
      iata: 'DUB',
      icao: 'EIDW',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T10:00:00+01:00',
      estimated: '2024-01-15T10:00:00+01:00',
      actual: '2024-01-15T10:00:00+01:00',
      estimated_runway: '2024-01-15T10:00:00+01:00',
      actual_runway: '2024-01-15T10:00:00+01:00',
    },
    arrival: {
      airport: 'Larnaca International Airport',
      timezone: 'Asia/Nicosia',
      iata: 'LCA',
      icao: 'LCLK',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T17:00:00+03:00',
      estimated: '2024-01-15T17:00:00+03:00',
      actual: '',
      estimated_runway: '',
      actual_runway: '',
    },
    airline: {
      iata: 'FR',
      icao: 'RYR',
      name: 'Ryanair',
      logo: '/logos/ryanair.svg'
    },
    flight: {
      number: '1782',
      iata: 'RN1782',
      icao: 'RYR1782',
      codeshared: {},
    },
    aircraft: {
      registration: 'D-AISP',
      iata: 'B738',
      icao: 'B738',
      icao24: '',
    },
    live: {
      updated: new Date().toISOString(),
      latitude: 53.4213,
      longitude: -6.2603,
      altitude: 11200,
      direction: 0,
      speed_horizontal: 840,
      speed_vertical: 0,
      is_ground: false,
    },
    progress: 40,
  },
  {
    flight_date: '2024-01-15',
    flight_status: 'active' as FlightStatus,
    departure: {
      airport: "Nice Côte d'Azur Airport",
      timezone: 'Europe/Paris',
      iata: 'NCE',
      icao: 'LFMN',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T09:00:00+02:00',
      estimated: '2024-01-15T09:00:00+02:00',
      actual: '2024-01-15T09:00:00+02:00',
      estimated_runway: '2024-01-15T09:00:00+02:00',
      actual_runway: '2024-01-15T09:00:00+02:00',
    },
    arrival: {
      airport: 'Tbilisi International Airport',
      timezone: 'Asia/Tbilisi',
      iata: 'TBS',
      icao: 'UGTB',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T14:30:00+04:00',
      estimated: '2024-01-15T14:30:00+04:00',
      actual: '',
      estimated_runway: '',
      actual_runway: '',
    },
    airline: {
      iata: 'S7',
      icao: 'SBI',
      name: 'S7 Airlines',
      logo: '/logos/s7.svg'
    },
    flight: {
      number: '124',
      iata: 'S7124',
      icao: 'SBI124',
      codeshared: {},
    },
    aircraft: {
      registration: 'RA-73415',
      iata: 'A20N',
      icao: 'A20N',
      icao24: '',
    },
    live: {
      updated: new Date().toISOString(),
      latitude: 43.6584,
      longitude: 7.2589,
      altitude: 10900,
      direction: 0,
      speed_horizontal: 860,
      speed_vertical: 0,
      is_ground: false,
    },
    progress: 25,
  },
  {
    flight_date: '2024-01-15',
    flight_status: 'active' as FlightStatus,
    departure: {
      airport: 'Francisco Sá Carneiro Airport',
      timezone: 'Europe/Lisbon',
      iata: 'OPO',
      icao: 'LPPR',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T07:00:00+01:00',
      estimated: '2024-01-15T07:00:00+01:00',
      actual: '2024-01-15T07:00:00+01:00',
      estimated_runway: '2024-01-15T07:00:00+01:00',
      actual_runway: '2024-01-15T07:00:00+01:00',
    },
    arrival: {
      airport: 'Heydar Aliyev International Airport',
      timezone: 'Asia/Baku',
      iata: 'GYD',
      icao: 'UBBB',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T16:00:00+04:00',
      estimated: '2024-01-15T16:00:00+04:00',
      actual: '',
      estimated_runway: '',
      actual_runway: '',
    },
    airline: {
      iata: 'LX',
      icao: 'SWR',
      name: 'SWISS',
      logo: '/logos/swiss.svg'
    },
    flight: {
      number: '318',
      iata: 'LX318',
      icao: 'SWR318',
      codeshared: {},
    },
    aircraft: {
      registration: 'HB-JHK',
      iata: 'BCS3',
      icao: 'BCS3',
      icao24: '',
    },
    live: {
      updated: new Date().toISOString(),
      latitude: 41.2481,
      longitude: -8.611,
      altitude: 10700,
      direction: 0,
      speed_horizontal: 830,
      speed_vertical: 0,
      is_ground: false,
    },
    progress: 55,
  },
  {
    flight_date: '2024-01-15',
    flight_status: 'active' as FlightStatus,
    departure: {
      airport: 'Burgas Airport',
      timezone: 'Europe/Sofia',
      iata: 'BOJ',
      icao: 'LBBG',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T06:00:00+03:00',
      estimated: '2024-01-15T06:00:00+03:00',
      actual: '2024-01-15T06:00:00+03:00',
      estimated_runway: '2024-01-15T06:00:00+03:00',
      actual_runway: '2024-01-15T06:00:00+03:00',
    },
    arrival: {
      airport: 'Muscat International Airport',
      timezone: 'Asia/Muscat',
      iata: 'MCT',
      icao: 'OOMS',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T14:00:00+04:00',
      estimated: '2024-01-15T14:00:00+04:00',
      actual: '',
      estimated_runway: '',
      actual_runway: '',
    },
    airline: {
      iata: 'LH',
      icao: 'DLH',
      name: 'Lufthansa',
      logo: '/logos/lufthansa.svg'
    },
    flight: {
      number: '401',
      iata: 'LH401',
      icao: 'DLH401',
      codeshared: {},
    },
    aircraft: {
      registration: 'D-AIXD',
      iata: 'A359',
      icao: 'A359',
      icao24: '',
    },
    live: {
      updated: new Date().toISOString(),
      latitude: 42.5698,
      longitude: 27.5159,
      altitude: 11300,
      direction: 0,
      speed_horizontal: 890,
      speed_vertical: 0,
      is_ground: false,
    },
    progress: 30,
  },
  {
    flight_date: '2024-01-15',
    flight_status: 'active' as FlightStatus,
    departure: {
      airport: 'Adolfo Suárez Madrid–Barajas Airport',
      timezone: 'Europe/Madrid',
      iata: 'MAD',
      icao: 'LEMD',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T11:00:00+01:00',
      estimated: '2024-01-15T11:00:00+01:00',
      actual: '2024-01-15T11:00:00+01:00',
      estimated_runway: '2024-01-15T11:00:00+01:00',
      actual_runway: '2024-01-15T11:00:00+01:00',
    },
    arrival: {
      airport: 'Leonardo da Vinci–Fiumicino Airport',
      timezone: 'Europe/Rome',
      iata: 'FCO',
      icao: 'LIRF',
      terminal: '',
      gate: '',
      delay: 0,
      scheduled: '2024-01-15T13:30:00+02:00',
      estimated: '2024-01-15T13:30:00+02:00',
      actual: '',
      estimated_runway: '',
      actual_runway: '',
    },
    airline: {
      iata: 'LH',
      icao: 'DLH',
      name: 'Lufthansa',
      logo: '/logos/lufthansa.svg'
    },
    flight: {
      number: '128',
      iata: 'AF128',
      icao: 'DLH128',
      codeshared: {},
    },
    aircraft: {
      registration: 'F-GZCP',
      iata: 'A359',
      icao: 'A359',
      icao24: '',
    },
    live: {
      updated: new Date().toISOString(),
      latitude: 40.4722,
      longitude: -3.5676,
      altitude: 11000,
      direction: 0,
      speed_horizontal: 880,
      speed_vertical: 0,
      is_ground: false,
    },
    progress: 80,
  },
];

export const ISO_COUNTRIES: Record<string, string> = {
  'AF': 'Afghanistan',
  'AL': 'Albania',
  'DZ': 'Algeria',
  'AD': 'Andorra',
  'AO': 'Angola',
  'AG': 'Antigua and Barbuda',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BS': 'Bahamas',
  'BH': 'Bahrain',
  'BD': 'Bangladesh',
  'BB': 'Barbados',
  'BY': 'Belarus',
  'BE': 'Belgium',
  'BZ': 'Belize',
  'BJ': 'Benin',
  'BT': 'Bhutan',
  'BO': 'Bolivia',
  'BA': 'Bosnia and Herzegovina',
  'BW': 'Botswana',
  'BR': 'Brazil',
  'BN': 'Brunei',
  'BG': 'Bulgaria',
  'BF': 'Burkina Faso',
  'BI': 'Burundi',
  'CV': 'Cape Verde',
  'KH': 'Cambodia',
  'CM': 'Cameroon',
  'CA': 'Canada',
  'CF': 'Central African Republic',
  'TD': 'Chad',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Colombia',
  'KM': 'Comoros',
  'CG': 'Congo',
  'CD': 'Congo (Democratic Republic)',
  'CR': 'Costa Rica',
  'HR': 'Croatia',
  'CU': 'Cuba',
  'CY': 'Cyprus',
  'CZ': 'Czech Republic',
  'DK': 'Denmark',
  'DJ': 'Djibouti',
  'DM': 'Dominica',
  'DO': 'Dominican Republic',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'SV': 'El Salvador',
  'GQ': 'Equatorial Guinea',
  'ER': 'Eritrea',
  'EE': 'Estonia',
  'SZ': 'Eswatini',
  'ET': 'Ethiopia',
  'FJ': 'Fiji',
  'FI': 'Finland',
  'FR': 'France',
  'GA': 'Gabon',
  'GM': 'Gambia',
  'GE': 'Georgia',
  'DE': 'Germany',
  'GH': 'Ghana',
  'GR': 'Greece',
  'GD': 'Grenada',
  'GT': 'Guatemala',
  'GN': 'Guinea',
  'GW': 'Guinea-Bissau',
  'GY': 'Guyana',
  'HT': 'Haiti',
  'HN': 'Honduras',
  'HU': 'Hungary',
  'IS': 'Iceland',
  'IN': 'India',
  'ID': 'Indonesia',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JP': 'Japan',
  'JO': 'Jordan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KI': 'Kiribati',
  'KP': 'North Korea',
  'KR': 'South Korea',
  'KW': 'Kuwait',
  'KG': 'Kyrgyzstan',
  'LA': 'Laos',
  'LV': 'Latvia',
  'LB': 'Lebanon',
  'LS': 'Lesotho',
  'LR': 'Liberia',
  'LY': 'Libya',
  'LI': 'Liechtenstein',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'MG': 'Madagascar',
  'MW': 'Malawi',
  'MY': 'Malaysia',
  'MV': 'Maldives',
  'ML': 'Mali',
  'MT': 'Malta',
  'MH': 'Marshall Islands',
  'MR': 'Mauritania',
  'MU': 'Mauritius',
  'MX': 'Mexico',
  'FM': 'Micronesia',
  'MD': 'Moldova',
  'MC': 'Monaco',
  'MN': 'Mongolia',
  'ME': 'Montenegro',
  'MA': 'Morocco',
  'MZ': 'Mozambique',
  'MM': 'Myanmar',
  'NA': 'Namibia',
  'NR': 'Nauru',
  'NP': 'Nepal',
  'NL': 'Netherlands',
  'NZ': 'New Zealand',
  'NI': 'Nicaragua',
  'NE': 'Niger',
  'NG': 'Nigeria',
  'MK': 'North Macedonia',
  'NO': 'Norway',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PW': 'Palau',
  'PS': 'Palestine',
  'PA': 'Panama',
  'PG': 'Papua New Guinea',
  'PY': 'Paraguay',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PL': 'Poland',
  'PT': 'Portugal',
  'QA': 'Qatar',
  'RO': 'Romania',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'KN': 'Saint Kitts and Nevis',
  'LC': 'Saint Lucia',
  'VC': 'Saint Vincent and the Grenadines',
  'WS': 'Samoa',
  'SM': 'San Marino',
  'ST': 'Sao Tome and Principe',
  'SA': 'Saudi Arabia',
  'SN': 'Senegal',
  'RS': 'Serbia',
  'SC': 'Seychelles',
  'SL': 'Sierra Leone',
  'SG': 'Singapore',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'SB': 'Solomon Islands',
  'SO': 'Somalia',
  'ZA': 'South Africa',
  'ES': 'Spain',
  'LK': 'Sri Lanka',
  'SD': 'Sudan',
  'SR': 'Suriname',
  'SE': 'Sweden',
  'CH': 'Switzerland',
  'SY': 'Syria',
  'TW': 'Taiwan',
  'TJ': 'Tajikistan',
  'TZ': 'Tanzania',
  'TH': 'Thailand',
  'TL': 'Timor-Leste',
  'TG': 'Togo',
  'TO': 'Tonga',
  'TT': 'Trinidad and Tobago',
  'TN': 'Tunisia',
  'TR': 'Turkey',
  'TM': 'Turkmenistan',
  'TV': 'Tuvalu',
  'UG': 'Uganda',
  'UA': 'Ukraine',
  'AE': 'United Arab Emirates',
  'GB ': 'United Kingdom',
  'US': 'United States',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VU': 'Vanuatu',
  'VE': 'Venezuela',
  'VN': 'Vietnam',
  'YE': 'Yemen',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe'
};
